### ISSUE TITLE
Include toggle for sound

### ISSUE THREAD

**Issue by lolsteve** [wuwentao/midea_ac_lan#246]
### Device type and model (or SN)

Air Conidtioner Unknown

### The description of new feature

Hello.

The Midea SmartHome app has the option to enable and disable sounds made by the device when a setting is changed.

Would it be possible to add support for this toggle?

![Screenshot_20240717-135324](https://github.com/user-attachments/assets/bfa4fa6a-2d85-413a-96ca-eadfb5cbb550)

The setting resets whenever the device is removed from power and I would like to automate turning it off when power is restored. Thanks!

**Comment by wuwentao** [comment]
it should be a supported feature in most of the AC device, the name should be `Prompt Tone` and should be available in `Extra Control` option(if your device support it, I'm not sure with your device detail, as there is too many AC model)

**Comment by BenJewell** [comment]
Can you please give more details? Older versions on the integration let me change the default to false in the code. But it seems to once again be getting set to true now after every update.

**Comment by lolsteve** [comment]
I setup an automation to turn it off anytime it is turned on.

```
alias: Turn off AC prompt tone
description: ""
mode: single
triggers:
  - entity_id:
      - climate.<entity_id>
    attribute: prompt_tone
    to: true
    trigger: state
conditions: []
actions:
  - data:
      device_id: <device_id>
      attribute: prompt_tone
      value: false
    action: midea_ac_lan.set_attribute
```
