### ISSUE TITLE
Fan speed not working from HomeKit

### ISSUE THREAD

**Issue by Buniculbroscoi** [wuwentao/midea_ac_lan#71]
### HA core version

2024.5.5

### Integration version

0.4.1

### Device type and model

Inventor Omnia eco

### Used App

Msmarthome

### The description of problem

Fan speed is not working in HomeKit. I can see the fan speed slider, but setting it to any level does not transfer the command to the unit.

**Comment by chemelli74** [comment]
Please add the following to `configuration.yaml` , restart HA, and post the log:
```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midea_local: info
 ```
Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

And add diagnostics (menu configuration -> integration -> midea_ac_lan -> download diagnostics )
