### ISSUE TITLE
The washing machine sensor cannot be displayed normally in homekit

### ISSUE THREAD

**Issue by lwydyby** [wuwentao/midea_ac_lan#92]
### HA Version
2024.5.4

###  Integration Version
v0.4.1

###  Device Type and Model
Front Load Washer 38124999 (14404)

###  App in Use
Midea MSmartHome

### Detailed Issue Description

After adding the washer and dryer to the HA dashboard, they display correctly.
![image](https://github.com/wuwentao/midea_ac_lan/assets/30611869/d07cfece-205f-4672-a69d-7f6d63018d68)
However, when I connect the sensors to Homekit via the Homekit bridge, they do not display correctly in the Home app.Currently, I have simulated two sensors for the washing machine as a binary_sensor and a temperature sensor, but displaying time with a temperature sensor doesn't feel user-friendly. The configuration is as follows:
```yaml
input_select:
  washing_machine_status:
    name: 洗衣机状态
    options:
      - "空闲"
      - "洗涤"
      - "漂洗"
      - "甩干"
    initial: "空闲"
    


automation:
  - alias: 更新洗衣机状态
    trigger:
      - platform: state
        entity_id: sensor.188016xxx26566_progress
    action:
      - service: input_select.select_option
        target:
          entity_id: input_select.washing_machine_status
        data:
          option: >
            {% set step = states('sensor.188016xxx826566_progress') %}
            {% if step == 'Idle' %}
              空闲
            {% elif step == 'Wash' %}
              洗涤
            {% elif step == 'Rinse' %}
              漂洗
            {% elif step == 'Spin' %}
              甩干
            {% else %}
              未知
            {% endif %}
  
sensor:
  - platform: template
    sensors:
      washing_machine_remaining_time_as_temperature:
        friendly_name: "洗衣机剩余时间"
        unit_of_measurement: "°C"
        value_template: >
          {% set time_remaining = states('sensor.18801648xxx6566_time_remaining') %}
          {% if time_remaining in ['未知', 'unavailable', '', 'unknown'] %}
            0
          {% else %}
            {{ time_remaining | int }}
          {% endif %}

binary_sensor:
  - platform: template
    sensors:
      washing_machine_idle:
        friendly_name: "空闲"
        value_template: "{{ is_state('input_select.washing_machine_status', '空闲') }}"

      washing_machine_wash:
        friendly_name: "洗涤"
        value_template: "{{ is_state('input_select.washing_machine_status', '洗涤') }}"

      washing_machine_rinse:
        friendly_name: "漂洗"
        value_template: "{{ is_state('input_select.washing_machine_status', '漂洗') }}"

      washing_machine_spin:
        friendly_name: "甩干"
        value_template: "{{ is_state('input_select.washing_machine_status', '甩干') }}"
```
Is there any way to make the sensors display correctly in Homekit?
